[package]
name = "aria2xspf"
version = "0.1.0"
authors = ["shimunn <>"]
edition = "2018"

[dependencies]
xml-rs = "0.8.0"
derive_builder = "0.7.1"
structopt = "0.2.15"
toml = "0.5.0"
serde_derive = "1.0.90"
dirs = "1.0.5"
serde = "1.0.90"
lazy_static = "1.3.0"
